# Generated by Django 2.0.1 on 2018-02-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materias',
            fields=[
                ('Codigo', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=150)),
                ('Grupo', models.PositiveSmallIntegerField(default=1)),
                ('Creditos', models.PositiveSmallIntegerField()),
                ('Profesor', models.CharField(blank=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Notas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Porcentaje', models.PositiveIntegerField()),
                ('Nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Fijar', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('Numero', models.AutoField(primary_key=True, serialize=False)),
                ('Materia', models.ManyToManyField(related_name='Semestre', to='calificaciones.Materias')),
            ],
        ),
        migrations.CreateModel(
            name='SubNotas',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=150)),
                ('Porcentaje', models.PositiveIntegerField()),
                ('Nota', models.DecimalField(decimal_places=1, max_digits=2)),
                ('Fijar', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='notas',
            name='SubNotas',
            field=models.ManyToManyField(blank=True, related_name='Notas', to='calificaciones.SubNotas'),
        ),
        migrations.AddField(
            model_name='materias',
            name='Notas',
            field=models.ManyToManyField(blank=True, related_name='Materia', to='calificaciones.Notas'),
        ),
    ]
